<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [2]:
# before everything, import these libraries (Shift-Enter)

from IPython.lib.display import YouTubeVideo

# II. Coding Projects > TITLE


<hr>
&nbsp;

In [1]:
import numpy as np
import xarray as xr
from fractions import Fraction
from dataclasses import dataclass
import plotly.graph_objects as go

In [2]:
def nparange(start, end, step, dtype=np.float32):
    """Modified np.arange()
        - improve float precision
        - includes endpoint

    Args:
        start, end, step: float (end is included in array)

    Returns:
        ndarray
    """
    frac = Fraction("{0:.20f}".format(step))
    delta = frac.numerator   # new step
    zoom = frac.denominator  # zoom to avoid float precision error
    if zoom > 1e20:
        print("WARNING: Ensure that step is a rational number"
            " to avoid floating errors")
    res = np.arange(start * zoom, end * zoom + delta, delta) / zoom
    return res.astype(dtype, casting='same_kind') 

In [3]:
Ux = nparange(-4, 4, 1)
Uy = nparange(-5, 5, 2)
Vx = nparange(0,10,2)
Vy = nparange(1,11, 1.5)

In [131]:
A = np.array([Ux[:, None] + Vx, Ux[:, None] - Vx])
A.shape

(2, 9, 6)

In [145]:
xr.DataArray(
    np.array([Ux[:, None] + Vx, Uy[:, None] + Vy]),
    dims=("dim", "Ux", "Vx"),
    coords={"Ux": Ux,
            "Vx": Vx,
            "dim": ["x", "y"]}
)

/tmp/ipykernel_158512/3992114723.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([Ux[:, None] + Vx, Uy[:, None] + Vy]),


ValueError: different number of dimensions on data and dims: 1 vs 3

In [147]:
datax = xr.DataArray(
    Ux[:, None] + Vx,
    dims=("Ux", "Vx"),
    coords={"Ux": Ux,
            "Vx": Vx}
)

datay = xr.DataArray(
    Uy[:, None] + Vy,
    dims=("Uy", "Vy"),
    coords={"Uy": Uy,
            "Vy": Vy}
)

return xr.Dataset({"x": datax, "y":datay})

In [155]:
ds = xr.Dataset({"x": datax, "y":datay})
ds

<xarray.Dataset>
Dimensions:  (Ux: 9, Vx: 6, Uy: 6, Vy: 8)
Coordinates:
  * Ux       (Ux) float32 -4.0 -3.0 -2.0 -1.0 0.0 1.0 2.0 3.0 4.0
  * Vx       (Vx) float32 0.0 2.0 4.0 6.0 8.0 10.0
  * Uy       (Uy) float32 -5.0 -3.0 -1.0 1.0 3.0 5.0
  * Vy       (Vy) float32 1.0 2.5 4.0 5.5 7.0 8.5 10.0 11.5
Data variables:
    x        (Ux, Vx) float32 -4.0 -2.0 0.0 2.0 4.0 ... 6.0 8.0 10.0 12.0 14.0
    y        (Uy, Vy) float32 -4.0 -2.5 -1.0 0.5 2.0 ... 12.0 13.5 15.0 16.5

In [160]:
ds.y.sel(Uy=-5, Vy=11.5)

<xarray.DataArray 'y' ()>
array(6.5, dtype=float32)
Coordinates:
    Uy       float32 -5.0
    Vy       float32 11.5

In [134]:
datax[0, 0]

<xarray.DataArray (Vx: 6)>
array([-4., -2.,  0.,  2.,  4.,  6.], dtype=float32)
Coordinates:
    Ux       float32 -4.0
  * Vx       (Vx) float32 0.0 2.0 4.0 6.0 8.0 10.0
    ops      <U3 'sum'

In [143]:
datax.sel(ops='sum', Ux=-4, Vx=10).values

array(6., dtype=float32)

In [144]:
datax.sel(ops='sub', Ux=-4, Vx=10).values

array(-14., dtype=float32)

In [55]:
A = np.arange(18).reshape(2,3,3)
A

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [56]:
A[:, None, :]

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]]],


       [[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]])

In [64]:
A = Ux[:, None] + Vx
A.shape

(9, 6)

In [59]:
datax = xr.DataArray(
    Ux[:, None] + Vx,
    dims=("Ux", "Vx"),
    coords={"Ux": Ux,
            "Vx": Vx}
)

In [72]:
datax

<xarray.DataArray (Ux: 9, Vx: 6)>
array([[-4., -2.,  0.,  2.,  4.,  6.],
       [-3., -1.,  1.,  3.,  5.,  7.],
       [-2.,  0.,  2.,  4.,  6.,  8.],
       [-1.,  1.,  3.,  5.,  7.,  9.],
       [ 0.,  2.,  4.,  6.,  8., 10.],
       [ 1.,  3.,  5.,  7.,  9., 11.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  5.,  7.,  9., 11., 13.],
       [ 4.,  6.,  8., 10., 12., 14.]], dtype=float32)
Coordinates:
  * Ux       (Ux) float32 -4.0 -3.0 -2.0 -1.0 0.0 1.0 2.0 3.0 4.0
  * Vx       (Vx) float32 0.0 2.0 4.0 6.0 8.0 10.0

In [69]:
datax.coords['Ux'][0]

<xarray.DataArray 'Ux' ()>
array(-4., dtype=float32)
Coordinates:
    Ux       float32 -4.0

In [76]:
datax[4,:].values

array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float32)