<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Getting-started" data-toc-modified-id="Getting-started-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Getting started</a></span><ul class="toc-item"><li><span><a href="#Load-NumPy" data-toc-modified-id="Load-NumPy-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Load NumPy</a></span></li><li><span><a href="#Built-in-documentation" data-toc-modified-id="Built-in-documentation-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Built-in documentation</a></span></li></ul></li><li><span><a href="#Creating-arrays" data-toc-modified-id="Creating-arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creating arrays</a></span><ul class="toc-item"><li><span><a href="#Creating-arrays-from-python-lists" data-toc-modified-id="Creating-arrays-from-python-lists-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Creating arrays from python lists</a></span></li><li><span><a href="#Creating-arrays-with-built-in-methods" data-toc-modified-id="Creating-arrays-with-built-in-methods-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Creating arrays with built-in methods</a></span></li></ul></li><li><span><a href="#Accessing-and-viewing-arrays" data-toc-modified-id="Accessing-and-viewing-arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Accessing and viewing arrays</a></span><ul class="toc-item"><li><span><a href="#Array-attributes" data-toc-modified-id="Array-attributes-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Array attributes</a></span></li><li><span><a href="#Array-indexing" data-toc-modified-id="Array-indexing-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Array indexing</a></span></li><li><span><a href="#Array-slicing" data-toc-modified-id="Array-slicing-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Array slicing</a></span></li><li><span><a href="#Indexing-in-3D" data-toc-modified-id="Indexing-in-3D-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Indexing in 3D</a></span></li><li><span><a href="#Fancy-indexing" data-toc-modified-id="Fancy-indexing-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Fancy indexing</a></span></li><li><span><a href="#Flattening-and-reshaping-arrays" data-toc-modified-id="Flattening-and-reshaping-arrays-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Flattening and reshaping arrays</a></span></li><li><span><a href="#Comparison-and-Boolean-mask" data-toc-modified-id="Comparison-and-Boolean-mask-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Comparison and Boolean mask</a></span></li><li><span><a href="#Searching" data-toc-modified-id="Searching-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>Searching</a></span></li></ul></li><li><span><a href="#Manipulating-arrays-and-computation" data-toc-modified-id="Manipulating-arrays-and-computation-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Manipulating arrays and computation</a></span><ul class="toc-item"><li><span><a href="#Vectorization-and-ufuncs" data-toc-modified-id="Vectorization-and-ufuncs-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Vectorization and ufuncs</a></span></li><li><span><a href="#Numpy-operators-and-ufunc" data-toc-modified-id="Numpy-operators-and-ufunc-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Numpy operators and ufunc</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#Stacking-and-concatening-arrays" data-toc-modified-id="Stacking-and-concatening-arrays-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Stacking and concatening arrays</a></span></li><li><span><a href="#Splitting-arrays" data-toc-modified-id="Splitting-arrays-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Splitting arrays</a></span></li><li><span><a href="#Moving-and-swaping-axis" data-toc-modified-id="Moving-and-swaping-axis-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Moving and swaping axis</a></span></li><li><span><a href="#And-more" data-toc-modified-id="And-more-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>And more</a></span></li></ul></li></ul></div>

## Getting started

### Load NumPy

In [3]:
import numpy as np

In [2]:
np.__version__

'1.21.0'

&nbsp;

### Built-in documentation

&nbsp;  

Use **tab-completion** if you want to access the list of available functions of the NumPy library

```ipython
In [3]: np.<TAB>
```

&nbsp;  

Use **?** if you want to access NumPy's built-in documentation

```ipython
In [4]: np?
```

```ipython
In [5]: np.abs?
```

&nbsp;

## Creating arrays

### Creating arrays from python lists

In [3]:
# 1D array (Option 1)
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
# 1D array (Option 2)
my_list = [1, 4, 2, 5, 3]
np.array(my_list)

array([1, 4, 2, 5, 3])

In [5]:
# 2D array
my_list = [[1,2,3],[4,5,6]]
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# when creating an array, the data needs to be of the same type
# If no match, NumPy will upcast it (if possible)
np.array([1, 4.001])

array([1.   , 4.001])

In [7]:
# use the 'dtype' keyword to set the data type explicitly
np.array([1, 2, 3, 4], dtype='float64')

array([1., 2., 3., 4.])

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

&nbsp;

### Creating arrays with built-in methods

![basic array creation](./attachments/np_creating-array.png)

- zeros()
- ones()
- full()
- empty()
- repeat()
- eye()

In [8]:
# Create a length-10 integer array filled with zeros
np.zeros(shape=10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# which is equivalent to
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create a 3x5 floating-point array filled with ones
# shape = (nb rows, nb columns)
np.ones(shape=(3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# which is also equivalent to
np.ones((3, 5), float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Create a 3x2x4 floating-point array filled with zeros
np.zeros((3,2,4), float)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([0., 0., 0.])

In [15]:
# the identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# repeat 4x the elements of an array
np.repeat([0, 1, 2], 4, axis=0)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [17]:
# repeat 4x an array
np.repeat([[0, 1, 2]], 4, axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

![more array creation](./attachments/np_arange-linspace.png)

- arange()
- linspace()


In [18]:
# Create an array filled with a linear sequence
# (this is similar to the built-in range() function)
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
# Starting at 2 ending at 5 (excluded)
np.arange(2,5)

array([2, 3, 4])

In [20]:
# Starting at 0, ending at -10 (excluded), steps of -2
np.arange(0,-10,-2)

array([ 0, -2, -4, -6, -8])

In [21]:
# Create an array of 5 values evenly spaced between 0 and 1 (included)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

![basic array creation](./attachments/np_arange-linspace-behavior.png)

Mind the behavior of `np.arange` when handling floats

![even more array creation](./attachments/np_random.png)

- random.random()
- random.rand()
- random.normal()
- random.randint()

In [22]:
# Create a 2x5 array with random values from a UNIFORM  distribution over [0, 1)
np.random.random((2, 5))

array([[0.45588416, 0.14246576, 0.08675487, 0.87156847, 0.23390309],
       [0.7879721 , 0.19743351, 0.64255598, 0.55010338, 0.34653625]])

In [23]:
# which is the same as this
np.random.rand(2,5)

array([[0.84221066, 0.49647041, 0.0566638 , 0.59886105, 0.23634358],
       [0.84389707, 0.42689731, 0.99031911, 0.4895688 , 0.87543812]])

In [24]:
# Create a 2x5 array with random values from a NORMAL distribution 
# (mean = 0 and standard deviation = 1)
np.random.normal(0, 1, (2, 5))

array([[-1.8333086 , -1.0484239 , -0.09049543,  0.85689954, -0.34951302],
       [ 1.36662348,  0.47284097,  0.13807923,  0.55764854,  0.69951205]])

In [25]:
# Create a 2x5 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (2, 5))

array([[6, 4, 5, 2, 9],
       [2, 0, 7, 7, 4]])

And for array of dimension 3:
![3D array creation](./attachments/np_creating-array3D.png)

&nbsp;

Check the [numpy documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) for more information on array creation.

&nbsp;
<hr>

## Accessing and viewing arrays


### Array attributes

In [51]:
np.random.seed(0)  # seed(0) ensures the same arrays will be produced each time

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.array([[1, 2, 3],          # Two-dimensional array
               [4, 5, 6],
               [7, 8, 9]])
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [27]:
# use .dtype to find the data type of the matrix
x3.dtype

dtype('int64')

In [28]:
# use .ndim to find how many dimensions has the matrix
x3.ndim

3

In [29]:
# use .shape to find the size of each dimension of the matrix 
x3.shape

(3, 4, 5)

In [30]:
# use .size to find the total size of the array
x3.size

60

**Confusion possible:** you may have noticed that we gave a tuple to the argument ```size``` in ```randint()```  
```np.random.randint(10, ```**```size```**```=(3, 4))```

In this case the **argument** 'size' of the function just happened to have the same name as the **attribute** 'size' of the numpy array. And this argument accepts tuples.

In [31]:
# use .itemsize to list the size (in bytes) of each array element
x3.itemsize

8

In [32]:
# use .nbytes to list the total size (in bytes) of the array
# usually = size x itemsize
x3.nbytes

480

&nbsp;

### Array indexing



In [52]:
# for 1D array, access indexes the same way as python list
print(x1)
print(x1[0])
print(x1[4])
print(x1[-2])
print(x1[-1])

[5 0 3 3 7 9]
5
7
7
9


In [36]:
# for multi-dimensional arrays
print(x2)
print(x2[0,0])
print(x2[0,3])
print(x2[-1,-1])

3
4
7


In [37]:
# to modify values
x2[0, 0] = 5000
x2

array([[5000,    5,    2,    4],
       [   7,    6,    8,    8],
       [   1,    6,    7,    7]])

In [38]:
# but NumPy arrays have a fixed type 
x2[0,0] = 3.14159  # this will be truncated!
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [39]:
x1

array([5, 0, 3, 3, 7, 9])

&nbsp;

### Array slicing

![Array indexing and slicing](./attachments/np_indexing.png)

In [40]:
# The NumPy slicing syntax follows that of the standard Python list
# first 3 elements
x1[:3]

array([5, 0, 3])

In [41]:
# elements after index 3
x1[3:]

array([3, 7, 9])

In [42]:
# middle sub-array
x1[2:5]

array([3, 3, 7])

In [43]:
# every other element
x1[::2]

array([5, 3, 7])

In [44]:
# every other element, starting at index 1
x1[1::2]

array([0, 3, 9])

In [45]:
# all elements, reversed
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [46]:
# reversed every other from index 4
x1[4::-2]

array([7, 3, 5])

In [47]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [48]:
# first 2 rows, first 3 columns
x2[:2, :3]  

array([[3, 5, 2],
       [7, 6, 8]])

In [49]:
# all rows, every other column
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [50]:
# reverse the matrix
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [51]:
# 1st row only
x2[0, :]

array([3, 5, 2, 4])

In [52]:
# also equivalent to
x2[0]

array([3, 5, 2, 4])

In [53]:
# 1st column only
x2[:, 0]

array([3, 7, 1])

**Note:** All of the indexing methods presented above (except fancy indexing, which we will see later) are actually so-called “views”: They don’t store the data and reflect the changes in the original array if it happens to get changed after being indexed.

In [54]:
# be careful, numpy slices are NOT copies !
# this allow to access and process pieces of large
# datasets without copying everything in the data buffer
A = x2[:2, :2]
A[0, 0] = 1000

In [55]:
x2

array([[1000,    5,    2,    4],
       [   7,    6,    8,    8],
       [   1,    6,    7,    7]])

In [56]:
# use .copy() if you do not want to modify inplace
A = x2[:2, :2].copy()
A[0, 0] = -314

In [57]:
x2

array([[1000,    5,    2,    4],
       [   7,    6,    8,    8],
       [   1,    6,    7,    7]])

&nbsp;

### Indexing in 3D

![boolean indexing](./attachments/np_2d-vs-3d-index.png)

In [56]:
a = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
              [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
              [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
a

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

Picking a row
![boolean indexing](./attachments/np_3d-array-index.png)

In [58]:
a[1, 2]

array([26, 27, 28])


![boolean indexing](./attachments/np_3d-array-index2.png)


In [59]:
a[0, :, 1]

array([11, 14, 17])

![boolean indexing](./attachments/np_3d-array-index3.png)


In [61]:
a[:, 1, 2]

array([15, 25, 35])

![boolean indexing](./attachments/np_3d-array-index4.png)


In [62]:
a[2]

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

![boolean indexing](./attachments/np_3d-array-index5.png)


In [63]:
a[:, 1]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

![boolean indexing](./attachments/np_3d-array-index6.png)

In [64]:
a[:, :, 0]

array([[10, 13, 16],
       [20, 23, 26],
       [30, 33, 36]])

&nbsp;

### Fancy indexing

![boolean indexing](./attachments/np_boolean-mask.png)

In [38]:
x = np.array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [39]:
# suppose we only want values at indexes 3, 7 and 4
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [40]:
# the shape of the index array influence the shape of the result
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [43]:
# What about higher dimension arrays?
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [44]:
# returns the elements at (0,2), (1,1), (2,3)
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
x[row, col]

array([ 2,  5, 11])

In [73]:
# we can also combine fancy and simple indices
x[2, [2, 0, 1]]

array([10,  8,  9])

In [75]:
# and combine fancy indexing with slicing
x[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

&nbsp;

### Flattening and reshaping arrays


In [79]:
my_list = [[1,2,3],[4,5,6]]
M = np.array(my_list)
M

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
# flatten the matrix to make it a row major 1D vector
M.flatten()

array([1, 2, 3, 4, 5, 6])

In [81]:
# ravel does (almost) the same
M.ravel()

array([1, 2, 3, 4, 5, 6])

In [82]:
# BUT:
# flatten() returns a copy of the original array, which means that
# ravel() is faster than flatten() since it does not occupy any memory.

R = M.ravel()
print(R)

F = M.flatten()
print(F)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [83]:
# if we change the raveled array, we also change the original array
R[0] = 1000
print(R)
print(M)

[1000    2    3    4    5    6]
[[1000    2    3]
 [   4    5    6]]


In [84]:
# but if we modify the flattened array, the original array is not affected.
F[-1] = 9999
print(F)
print(M)

[   1    2    3    4    5 9999]
[[1000    2    3]
 [   4    5    6]]


![reshaping](./attachments/np_reshape1.png)

In [66]:
# recall
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
# to reshape an array in any form use reshape()
x.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [68]:
x.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [69]:
# BUT it returns a new shape WITHOUT changing its data.
print(x.reshape(2,6).shape)
print(x.reshape(4,3).shape)
print(x.shape)

(2, 6)
(4, 3)
(3, 4)


In [88]:
A = np.array([2,0,1,8])
A

array([2, 0, 1, 8])

In [89]:
A.shape

(4,)

In [90]:
A.reshape(4,1)

array([[2],
       [0],
       [1],
       [8]])

In [91]:
A.shape

(4,)

In [71]:
# determine automatically the size with -1
x.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
x.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [92]:
# use newaxis to increase the dimension by 1
A[np.newaxis, :]

array([[2, 0, 1, 8]])

In [93]:
A[np.newaxis, :].shape

(1, 4)

In [94]:
A[:, np.newaxis].shape

(4, 1)

- `np.newaxis`, adds an empty axis at the designated place.
- `None` is a shortcut for `np.newaxis`
- -1 argument tells `reshape` to calculate one of the dimension sizes automatically 

![more reshaping](./attachments/np_reshape2.png)
![even more reshaping](./attachments/np_reshape3.png)
![even more reshaping](./attachments/np_3d-flatten-reshape.png)

&nbsp;

### Comparison and Boolean mask

![boolean indexing](./attachments/np_boolean-comparison.png)

In [7]:
x = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6]])

In [8]:
# which elements of x is less than 6
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [12]:
# are there any values greater than 8?
np.any(x > 8)

True

In [18]:
# Careful Python “ternary” comparisons don't work with numpy
np.any(3 < x < 6)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [13]:
# are all values less than 10?
np.all(x < 10)

True

In [14]:
# are all values equal to 6?
np.all(x == 6)

False

In [15]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

In [24]:
# remember that '~' = NOT
np.any(~(x == 0))  # is there any value NOT equal to 0

True

In [77]:
x = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6]])

In [78]:
# return the array of all values < 5
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [79]:
# using a boolean array as a mask on the rows
mask = np.array([1, 0, 1], dtype=bool)
x[mask]


array([[5, 0, 3, 3],
       [2, 4, 7, 6]])

In [80]:
# using a boolean array as a mask on the rows
mask = np.array([1, 0, 1, 0], dtype=bool)
x[:, mask]

array([[5, 3],
       [7, 3],
       [2, 7]])

In [81]:
# we can combine masking and fancy indexing
mask = np.array([1, 0, 1, 0], dtype=bool)
x[row[:, np.newaxis], mask]

array([[5, 3],
       [7, 3],
       [2, 7]])

&nbsp;

### Searching

![array searching](./attachments/np_lookup.png)


**Note:** As opposed to Python lists, a NumPy array does not have an index method.

- One way of finding an element is `np.where(a==x)[0][0]`, which is neither elegant nor fast as it needs to look through all elements of the array even if the item to find is in the very beginning.
- A faster way to do it is via accelerating `next((i[0] for i, v in np.ndenumerate(a) if v==x), -1)` with [Numba](https://numba.pydata.org/) (otherwise it’s way slower in the worst case than `where`).
- Once the array is sorted though, the situation gets better:`v = np.searchsorted(a, x); return v if a[v]==x else -1` is really fast with **O(log N)** complexity, but it requires O(N log N) time to sort first.

&nbsp;
<hr>

## Manipulating arrays and computation

### Vectorization and ufuncs

&nbsp;  

Computation on NumPy arrays can be very fast, or it can be very slow. 

Slowness happens in particuliar in situations where **many small operations** are being **repeated** – for instance looping over arrays to operate on each element.

In [60]:
# consider the following function f(x) = 1/x
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [61]:
# let's generate an array of size 10
values = np.random.randint(1, 10, size=5)
values

array([5, 4, 5, 5, 9])

In [62]:
# and we check the time it takes to calculate 1/x for each value of this array
%timeit  compute_reciprocals(values)

11.8 µs ± 2.77 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [63]:
# now we do the same for an array of size 1000000
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2 s ± 188 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


the bottleneck here is not the operations themselves, but the **type-checking** and function dispatches that must done at each cycle of the loop. 

Each time the reciprocal is computed, Python first examines the object's type and does a dynamic lookup of the correct function to use for that type.

If we were working in **compiled code** instead, this type specification would be known before the code executes and the result could be computed much **more efficiently**.

&nbsp;  
BUT the restriction of a NumPy array to have a **single data type** means mathematical operations can be **optimized**. We call this a **vectorized operation**.

This **vectorization** approach is implemented via **ufuncs**, whose main purpose is to quickly execute repeated operations by pushing the loop into the **compiled layer** that underlies NumPy

In [64]:
# compare this with earlier result
%timeit  1.0 / values
%timeit (1.0 / big_array)

994 ns ± 67.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2.69 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


&nbsp;  
Computations using vectorization through ufuncs are nearly **always more efficient than** their counterpart implemented using **Python loops**, especially as the arrays grow in size.

Any time you see such a loop in a Python script, check if you can **replace it with a vectorized expression**.

&nbsp;  

### Numpy operators and ufunc

&nbsp;  
A list of some operators implemented in NumPy and their equivalent universal functions:

| Operator | Equivalent ufunc     | Description                             |
| -------- | -------------------- | --------------------------------------- |
| ``+``    | ``np.add``           | Addition (e.g., ``1 + 1 = 2``)          |
| ``-``    | ``np.subtract``      | Subtraction (e.g., ``3 - 2 = 1``)       |
| ``-``    | ``np.negative``      | Unary negation (e.g., ``-2``)           |
| ``*``    | ``np.multiply``      | Multiplication (e.g., ``2 * 3 = 6``)    |
| ``/``    | ``np.divide``        | Division (e.g., ``3 / 2 = 1.5``)        |
| ``//``   | ``np.floor_divide``  | Floor division (e.g., ``3 // 2 = 1``)   |
| ``**``   | ``np.power``         | Exponentiation (e.g., ``2 ** 3 = 8``)   |
| ``%``    | ``np.mod``           | Modulus/remainder (e.g., ``9 % 4 = 1``) |
| ``==``   | ``np.equal``         | Truth value of (x1 == x2) element-wise. |
| ``!=``   | ``np.not_equal``     | Truth value of (x1 != x2) element-wise. |
| ``>``    | ``np.greater``       | Truth value of (x1 > x2) element-wise.  |
| ``>=``   | ``np.greater_equal`` | Truth value of (x1 >= x2) element-wise. |
| ``<``    | ``np.less``          | Truth value of (x1 < x2) element-wise.  |
| ``<=``   | ``np.less_equal``    | Truth value of (x1 <= x2) element-wise. |

Operations between an array and a number

![array number operations](./attachments/np_vector-scalar-operation.png)


Operations between 2 arrays:

![array array operations](./attachments/np_vectors-operation.png)


Operations between 2D arrays:

![matrix matrix operations](./attachments/np_matrix-operation1.png)

In [65]:
# Example
x = np.arange(4)
print("x      = ", x)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division

x      =  [0 1 2 3]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


**Note:** Beware of [floating-point errors](https://floating-point-gui.de/errors/comparison/) when computing.

![basic array creation](./attachments/np_compare-arrays.png)

In [58]:
# use np.allclose(a, b) to compare arrays
np.allclose(0.1+0.2, 0.3)

True

`np.allclose` assumes all the compared numbers to be of a typical scale of 1. For example, if you work with nanoseconds (=1e9 s), you need to divide the default `atol` argument value by 1e9 (in this case default atol value 1e8 * 1e9 = 1e17)

In [59]:
np.allclose(1e-9, 2e-9, atol=1e-17) == False

True

`math.isclose` makes no assumptions about the numbers to be compared but relies on a user to give a reasonable `abs_tol` value instead (taking the default `np.allclose atol` value of 1e-8 is good enough for numbers with a typical scale of 1).

Also, beware that some minor issues can arise with `np.allclose` (in some rare cases, it can behave [asymetrically](https://github.com/numpy/numpy/issues/10161))

&nbsp;

### Broadcasting

**Broadcasting** is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

![broadcasting](./attachments/np_broadcasting.png)

In [66]:
# for arrays of the same size, it is straightforward
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [67]:
# adding a scalar to an arrays is equivalent to stretching the dimension of the scalar
# i.e. 'broadcasting' it from 0 dimension to 1 dimension
print(a + 5)
print(a + b)

[5 6 7]
[5 6 7]


In [68]:
# here b is stretched from 1D to 2D
M = np.ones((3, 3))
M+b

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [69]:
# a more complicated example:
a = np.arange(3)
print(a)
print(a.shape)


[0 1 2]
(3,)


In [70]:
b = np.arange(3)[:, np.newaxis]
print(b)
print(b.shape)

[[0]
 [1]
 [2]]
(3, 1)


In [71]:
# here both a and b are being stretched to match a common shape
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

![more broadcasting](./attachments/np_broadcasting2.png)


**Rules of Broadcasting:**

- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is **padded** with ones on its leading (left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [72]:
M = np.ones((2, 3))
a = np.arange(3)

The shape of the arrays are

- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

We see by rule 1 that the array ``a`` has fewer dimensions, so we pad it on the left with ones:

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

By rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match:

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

The shapes match, and we see that the final shape will be ``(2, 3)``:

In [73]:
# the shapes are compatible
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [74]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

The shape of the arrays are:

- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

Rule 1 says we must pad the shape of ``b`` with ones:

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

Because the result matches, these shapes are compatible.

In [75]:
# the shapes are compatible
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [76]:
M = np.ones((3, 2))
a = np.arange(3)

The shape of the arrays are

- ``M.shape = (3, 2)``
- ``a.shape = (3,)``

Again, rule 1 tells us that we must pad the shape of ``a`` with ones:

- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``

By rule 2, the first dimension of ``a`` is stretched to match that of ``M``:

- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

Now we hit rule 3–the final shapes do not match, so these two arrays are NOT compatible, as we can observe by attempting this operation:

In [77]:
# the shapes are not compatible
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [78]:
# This would make the shapes compatible
M + a[:, np.newaxis]  # a.shape = (3,1)

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

&nbsp;

Check the [numpy documentation](https://numpy.org/doc/stable/reference/ufuncs.html) for more information on universal functions and broadcasting.

&nbsp;

### Stacking and concatening arrays

![stacking](./attachments/np_stacking1.png)

![more stacking](./attachments/np_stacking2.png)

![even more stacking](./attachments/np_stacking3.png)

In [95]:
# for 1D arrays
w = np.array([0, 0])
x = np.array([1, 2, 3])
y = np.array([20, 21, 22])
z = np.array([99, 99, 99])
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [96]:
# for arrays of mixed dimensions
# use vstack to vertically stack the arrays
np.vstack([z, grid])

array([[99, 99, 99],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [97]:
# stack the columns without needing to extend the dimension
np.column_stack([grid, w])

array([[1, 2, 3, 0],
       [4, 5, 6, 0]])

In [98]:
# whereas hstack won't work
np.hstack([grid, w])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [99]:
# hstack requires the arrays to the same 2nd dimension
np.hstack([grid, w[:, None]])

array([[1, 2, 3, 0],
       [4, 5, 6, 0]])

In [100]:
# use dstack to stack arrays along the third axis
np.dstack([x,y])

array([[[ 1, 20],
        [ 2, 21],
        [ 3, 22]]])

![concatenate](./attachments/np_concatenate.png)

In [101]:
np.concatenate([x, y, z])

array([ 1,  2,  3, 20, 21, 22, 99, 99, 99])

In [102]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [103]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

&nbsp;

### Splitting arrays

![splitting](./attachments/np_split.png)

In [104]:
x = [1, 2, 3, 99, 99, 20, 21, 22]

In [105]:
# use split() to split the array
# list as parameters = indexes at which to split
# note: n parameters --> n+1 arrays 
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([20, 21, 22])]

In [106]:
np.split(x, [4, 7])

[array([ 1,  2,  3, 99]), array([99, 20, 21]), array([22])]

In [107]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
# use vsplit() to split vertically
# list as parameters = indexes at which to split
# note: n parameters --> n+1 arrays 
np.vsplit(grid, [3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [109]:
# int as parameters = nb of output arrays
# BUT it needs to be EQUALLY dividable
np.vsplit(grid, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [110]:
def vsplit(grid, n):
    try:
        return np.vsplit(grid, n)
    except: 
        return "This does not work"

In [111]:
vsplit(grid,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [112]:
vsplit(grid,3)

'This does not work'

In [113]:
# use hsplit() to split horizontally
np.hsplit(grid, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [114]:
np.hsplit(grid, [1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [115]:
np.hsplit(grid, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [116]:
# similarly for dsplit()
print("grid =\n{}\n".format(grid))

A = grid.reshape(2, 2, 4)  # first let's reshape the array
print("A =\n{}\n".format(A))

np.dsplit(A, 2)  # and then apply dsplit()

grid =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

A =
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]



[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]),
 array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

&nbsp;

### Moving and swaping axis

![Move axes](./attachments/np_move-axes.png)

![Swap axes](./attachments/np_swap-axes.png)

&nbsp;

### And more

![replication](./attachments/np_replications.png)
![deletion](./attachments/np_delete.png)
![insertion](./attachments/np_insert.png)
![appending](./attachments/np_append.png)

**Note:** numpy arrays slower than lists when appending elements (contrary to python list, no space is reserved at the end of the array to facilitate quick appends). Solutions are:
- grow a Python list and convert it to a NumPy array when it is ready
- or preallocate the necessary space with np.zeros or np.empty

![padding](./attachments/np_pad.png)

&nbsp;

Check the [numpy documentation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html) for more information on array manipulation.

&nbsp;
<hr>
<h1><a id="credits"></a>Credits</h1>

&nbsp;  

This notebook is inspired by:
- [NumPy Illustrated: The Visual Guide to NumPy](https://hakk.gg/numpy-illustrated-the-visual-guide-to-numpy/)
- [Visual Numpy](https://jalammar.github.io/visual-numpy/)
- [Indexing and slicing numpy arrays](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/)
- [Reshape numpy arrays in Python — a step-by-step pictorial tutorial](https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b)
- [Python Data Science Handbook  by Jake Vanderplas](https://github.com/jakevdp/PythonDataScienceHandbook)