# Table of Content
    
 &nbsp;


- [Getting started](#0)
    - [Load NumPy](#0.1)
    - [Built-in documentation](#0.2)
    
 &nbsp;

- **[1. Creating arrays](#1)**
    - [1.1 Creating arrays from python lists](#1.1)
    - [1.2 Creating arrays with built-in methods](#1.2)
    
 &nbsp;

- **[2. Manipulating arrays](#2)**
    - [2.1 Array attributes](#2.1)
    - [2.2 Array indexing](#2.2)
    - [2.3 Array slicing](#2.3)
    - [2.4 Array reshaping](#2.4)
    - [2.5 Array concatenation](#2.5)
    - [2.6 Array splitting](#2.6)
    
 &nbsp;

- **[3. Computation using universal functions](#3)**
    - [3.1 Vectorization and ufuncs](#3.1)
    - [3.2 Array arithmetic](#3.2)  
    - [3.3 Absolute value](#3.3)
    - [3.4 Trigonometric functions](#3.4)
    - [3.5 Exponents and logarithms](#3.5)
    - [3.6 More functions](#3.6)
    - [3.7 Advanced Ufunc Features](#3.7)
    
 &nbsp;

- **[4. Computation using aggregations](#4)**


# <a id="0"></a>Getting started

## <a id="0.1"></a>Load NumPy

In [36]:
import numpy as np

In [37]:
np.__version__

'1.21.0'

&nbsp;

## <a id="0.2"></a>Built-in documentation

&nbsp;  

Use **tab-completion** if you want to access the list of available functions of the NumPy library

```ipython
In [3]: np.<TAB>
```

&nbsp;  

Use **?** if you want to access NumPy's built-in documentation

```ipython
In [4]: np?
```

```ipython
In [5]: np.abs?
```

&nbsp;

# <a id="1"></a>1. Creating arrays

## <a id="1.1"></a>1.1 Creating arrays from python lists

In [38]:
# 1D array (Option 1)
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [39]:
# 1D array (Option 2)
my_list = [1, 4, 2, 5, 3]
np.array(my_list)

array([1, 4, 2, 5, 3])

In [40]:
# 2D array
my_list = [[1,2,3],[4,5,6]]
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# flatten the matrix to make it a row major 1D vector
np.array(my_list).flatten()

array([1, 2, 3, 4, 5, 6])

In [42]:
# the data in the array need to be of the same type
# If not match, NumPy will upcast it (if possible)
np.array([1, 4.001])

array([1.   , 4.001])

In [43]:
# use the 'dtype' keyword to set the data type explicitly
np.array([1, 2, 3, 4], dtype='float64')

array([1., 2., 3., 4.])

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

&nbsp;

## <a id="1.2"></a>1.2 Creating arrays with built-in methods

- zeros()
- ones()
- full()
- repeat()
- empty()
- eye() (Identity matrix)
- arange()
- linspace()
- random.random()
- random.rand()
- random.normal()
- random.randint()


In [44]:
# Create a length-10 integer array filled with zeros
np.zeros(shape=10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
# which is equivalent to
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
# Create a 3x5 floating-point array filled with ones
# shape = (nb rows, nb columns)
np.ones(shape=(3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
# which is also equivalent to
np.ones((3, 5), float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
# Create a 3x2x4 floating-point array filled with zeros
np.zeros((3,2,4), float)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [49]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [113]:
# repeat 4x the elements of an array
np.repeat([0, 1, 2], 4, axis=0)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [114]:
# repeat 4x an array
np.repeat([[0, 1, 2]], 4, axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [50]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([0., 0., 0.])

In [60]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# Create an array filled with a linear sequence
# (this is similar to the built-in range() function)
np.arange(5)

array([0, 1, 2, 3, 4])

In [52]:
# Starting at 2 ending at 5 (excluded)
np.arange(2,5)

array([2, 3, 4])

In [31]:
# Starting at 0, ending at -10 (excluded), steps of -2
np.arange(0,-10,-2)

array([ 0, -2, -4, -6, -8])

In [53]:
# Create an array of 5 values evenly spaced between 0 and 1 (included)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [54]:
# Create a 2x5 array with random values from a UNIFORM  distribution over [0, 1)
np.random.random((2, 5))

array([[0.0353699 , 0.69267055, 0.86118145, 0.16810627, 0.80389846],
       [0.334036  , 0.54517286, 0.79699186, 0.67143252, 0.6287372 ]])

In [55]:
# which is the same as this
np.random.rand(2,5)

array([[0.80207705, 0.1216563 , 0.99771109, 0.47352265, 0.82730144],
       [0.62064205, 0.83369922, 0.10128149, 0.9696634 , 0.73250628]])

In [56]:
# Create a 2x5 array with random values from a NORMAL distribution 
# (mean = 0 and standard deviation = 1)
np.random.normal(0, 1, (2, 5))

array([[-0.36723426,  0.30798673, -1.51027462,  0.1560343 ,  0.81002506],
       [ 0.63120126,  0.41496836, -0.40696159, -1.65001469, -0.71068893]])

In [57]:
# Create a 2x5 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (2, 5))

array([[3, 1, 2, 1, 4],
       [3, 0, 3, 8, 2]])

&nbsp;
<hr>

# <a id="2"></a>2. Manipulating arrays


## <a id="2.1"></a>2.1 Array attributes

In [61]:
np.random.seed(0)  # seed(0) ensures the same arrays will be produced each time

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [62]:
# use .dtype to find the data type of the matrix
x3.dtype

dtype('int64')

In [63]:
# use .ndim to find how many dimensions has the matrix
x3.ndim

3

In [64]:
# use .shape to find the size of each dimension of the matrix 
x3.shape

(3, 4, 5)

In [65]:
# use .size to find the total size of the array
x3.size

60

**Confusion possible:** you may have noticed that we gave a tuple to the argument ```size``` in ```randint()```  
```np.random.randint(10, ```**```size```**```=(3, 4))```

In this case the **argument** 'size' of the function just happened to have the same name as the **attribute** 'size' of the numpy array. And this argument accepts tuples.

In [66]:
# use .itemsize to list the size (in bytes) of each array element
x3.itemsize

8

In [67]:
# use .nbytes to list the total size (in bytes) of the array
# usually = size x itemsize
x3.nbytes

480

&nbsp;

## <a id="2.2"></a>2.2 Array indexing

In [68]:
x1

array([5, 0, 3, 3, 7, 9])

In [69]:
# for 1D array, access indexes the same way as python list
print(x1[0])
print(x1[4])
print(x1[-2])
print(x1[-1])

5
7
7
9


In [70]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [71]:
# for multi-dimensional arrays
print(x2[0,0])
print(x2[0,3])
print(x2[-1,-1])

3
4
7


In [72]:
# to modify values
x2[0, 0] = 5000
x2

array([[5000,    5,    2,    4],
       [   7,    6,    8,    8],
       [   1,    6,    7,    7]])

In [73]:
# but NumPy arrays have a fixed type 
x2[0,0] = 3.14159  # this will be truncated!
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

&nbsp;

## <a id="2.3"></a>2.3 Array slicing

In [74]:
x1

array([5, 0, 3, 3, 7, 9])

In [75]:
# The NumPy slicing syntax follows that of the standard Python list
# first 3 elements
x1[:3]

array([5, 0, 3])

In [76]:
# elements after index 3
x1[3:]

array([3, 7, 9])

In [77]:
# middle sub-array
x1[2:5]

array([3, 3, 7])

In [78]:
# every other element
x1[::2]

array([5, 3, 7])

In [79]:
# every other element, starting at index 1
x1[1::2]

array([0, 3, 9])

In [80]:
# all elements, reversed
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [81]:
# reversed every other from index 4
x1[4::-2]

array([7, 3, 5])

In [82]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [83]:
# first 2 rows, first 3 columns
x2[:2, :3]  

array([[3, 5, 2],
       [7, 6, 8]])

In [84]:
# all rows, every other column
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [49]:
# reverse the matrix
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [50]:
# 1st row only
x2[0, :]

array([3, 5, 2, 4])

In [51]:
# also equivalent to
x2[0]

array([3, 5, 2, 4])

In [52]:
# 1st column only
x2[:, 0]

array([3, 7, 1])

In [53]:
# but be careful, numpy slices are NOT copies !
# this allow to access and process pieces of large
# datasets without copying everything in the data buffer
A = x2[:2, :2]
A[0, 0] = 1000

In [54]:
x2

array([[1000,    5,    2,    4],
       [   7,    6,    8,    8],
       [   1,    6,    7,    7]])

In [55]:
# use .copy() if you do not want to modify inplace
A = x2[:2, :2].copy()
A[0, 0] = -314

In [56]:
x2

array([[1000,    5,    2,    4],
       [   7,    6,    8,    8],
       [   1,    6,    7,    7]])

&nbsp;

## <a id="2.4"></a>2.4 Array reshaping

In [57]:
# use reshape() to reshape an array
x2.reshape(2,6)

array([[1000,    5,    2,    4,    7,    6],
       [   8,    8,    1,    6,    7,    7]])

In [58]:
x2.reshape(4,3)

array([[1000,    5,    2],
       [   4,    7,    6],
       [   8,    8,    1],
       [   6,    7,    7]])

In [59]:
# BUT it returns a new shape WITHOUT changing its data.
print(x2.reshape(2,6).shape)
print(x2.reshape(4,3).shape)
print(x2.shape)

(2, 6)
(4, 3)
(3, 4)


In [60]:
A = np.array([2,0,1,8])
A

array([2, 0, 1, 8])

In [61]:
A.shape

(4,)

In [62]:
A.reshape(4,1)

array([[2],
       [0],
       [1],
       [8]])

In [63]:
A.shape

(4,)

In [64]:
# use newaxis to increase the dimension by 1
A[np.newaxis, :]

array([[2, 0, 1, 8]])

In [65]:
A[np.newaxis, :].shape

(1, 4)

In [66]:
A[:, np.newaxis].shape

(4, 1)

&nbsp;

## <a id="2.5"></a>2.5 Array concatenation

In [85]:
# use concatenate()
x = np.array([1, 2, 3])
y = np.array([20, 21, 22])
z = np.array([99, 99, 99])
np.concatenate([x, y, z])

array([ 1,  2,  3, 20, 21, 22, 99, 99, 99])

In [86]:
# for multi-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [88]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [89]:
# for arrays of mixed dimensions
# use vstack to vertically stack the arrays
np.vstack([z, grid])

array([[99, 99, 99],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [90]:
# use hstack to horizontally stack the arrays
z = np.array([[99],
              [99]])
np.hstack([grid, z])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [73]:
# use dstack to stack arrays along the third axis
np.dstack([x,y])

array([[[ 1, 20],
        [ 2, 21],
        [ 3, 22]]])

&nbsp;

## <a id="2.6"></a>2.6 Array splitting

In [96]:
x = [1, 2, 3, 99, 99, 20, 21, 22]

In [97]:
# use split() to split the array
# list as parameters = indexes at which to split
# note: n parameters --> n+1 arrays 
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([20, 21, 22])]

In [98]:
np.split(x, [4, 7])

[array([ 1,  2,  3, 99]), array([99, 20, 21]), array([22])]

In [99]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
# use vsplit() to split vertically
# list as parameters = indexes at which to split
# note: n parameters --> n+1 arrays 
np.vsplit(grid, [3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [101]:
# int as parameters = nb of output arrays
# BUT it needs to be EQUALLY dividable
np.vsplit(grid, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [102]:
def vsplit(grid, n):
    try:
        return np.vsplit(grid, n)
    except: 
        return "This does not work"

In [103]:
vsplit(grid,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [104]:
vsplit(grid,3)

'This does not work'

In [83]:
# use hsplit() to split horizontally
np.hsplit(grid, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [84]:
np.hsplit(grid, [1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [85]:
np.hsplit(grid, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [106]:
# similarly for dsplit()
print("grid =\n{}\n".format(grid))

A = grid.reshape(2, 2, 4)  # first let's reshape the array
print("A =\n{}\n".format(A))

np.dsplit(A, 2)  # and then apply dsplit()

grid =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

A =
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]



[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]),
 array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

&nbsp;
<hr>

# <a id="3"></a>3. Computation using universal functions

&nbsp;  

Computation on NumPy arrays can be very fast, or it can be very slow. 

Slowness happens in particuliar in situations where **many small operations** are being **repeated** – for instance looping over arrays to operate on each element.

In [87]:
# consider the following function f(x) = 1/x
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [88]:
# let's generate an array of size 10
values = np.random.randint(1, 10, size=5)
values

array([5, 4, 5, 5, 9])

In [89]:
# and we check the time it takes to calculate 1/x for each value of this array
%timeit  compute_reciprocals(values)

11.1 µs ± 674 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [90]:
# now we do the same for an array of size 1000000
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.8 s ± 125 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


&nbsp;  
the bottleneck here is not the operations themselves, but the **type-checking** and function dispatches that must done at each cycle of the loop. 

Each time the reciprocal is computed, Python first examines the object's type and does a dynamic lookup of the correct function to use for that type.

If we were working in **compiled code** instead, this type specification would be known before the code executes and the result could be computed much **more efficiently**.

&nbsp;  

## <a id="3.1"></a>3.1 Vectorization and ufuncs


The restriction of a NumPy array to have a **single data type** means mathematical operations can be **optimized**. We call this a **vectorized operation**.

This **vectorization** approach is implemented via **ufuncs**, whose main purpose is to quickly execute repeated operations by pushing the loop into the **compiled layer** that underlies NumPy

In [91]:
# compare this with earlier result
%timeit  1.0 / values

927 ns ± 92.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [92]:
# compare this with earlier result
%timeit (1.0 / big_array)

1.8 ms ± 402 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


&nbsp;  
Computations using vectorization through ufuncs are nearly **always more efficient than** their counterpart implemented using **Python loops**, especially as the arrays grow in size.

Any time you see such a loop in a Python script, check if you can **replace it with a vectorized expression**.

&nbsp;  

## <a id="3.2"></a>3.2 Array arithmetic


In [93]:
# unary operations (1 variable)
x = np.arange(4)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [94]:
# binary operations (2 variables)
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division

x      = [0 1 2 3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


&nbsp;  
The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

Additionally there are Boolean/bitwise operators; we will explore these in [Comparisons, Masks, and Boolean Logic](#6)

&nbsp;  

## <a id="3.3"></a>3.3 Absolute value

In [95]:
# use Python abs()
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [96]:
# or NumPy abs()
np.abs(x)

array([2, 1, 0, 1, 2])

In [97]:
# also equivalent to
np.absolute(x)

array([2, 1, 0, 1, 2])

In [98]:
# This also works with complex numbers
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

&nbsp;  

## <a id="3.4"></a>3.4 Trigonometric functions

In [99]:
x = [0, np.pi/2, np.pi]
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


**NOTE:** The values are computed to within **machine precision**, which is why values that should be zero do **not always** hit exactly **zero**.

In [100]:
x = [-1, 0, 1]
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


&nbsp;  

## <a id="3.5"></a>3.5 Exponents and logarithms

In [101]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))      # but 2**x does not work
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [102]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [103]:
# expm and logNp are specialized versions that maintain precision with very small input
# They give more precise values than if the raw np.log or np.exp were to be used.
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


&nbsp;  

## <a id="3.6"></a>3.6 More functions

- Check [Numpy Routines Chapter](https://numpy.org/doc/stable/reference/routines.html) for a list of all the functions available
- Check [SciPy Special functions](https://docs.scipy.org/doc/scipy/reference/special.html) for even more specialized functions

&nbsp;  

## <a id="3.7"></a>3.7 Advanced Ufunc Features



In [104]:
# Specifying output
x = np.arange(5)
y = np.multiply(x, 10)
y

array([ 0, 10, 20, 30, 40])

In [105]:
# is similar to (but more memory efficient):
y = np.zeros(5, int)
np.multiply(x, 10, out=y)
y

array([ 0, 10, 20, 30, 40])

In [106]:
# which can be used in more complex ways
y = np.zeros(10, int)
np.power(2, x, out=y[::2])  # update every other element
y

array([ 1,  0,  2,  0,  4,  0,  8,  0, 16,  0])

Wheras when we do:

```y[::2] = 2 ** x```

1) we create a temporary array to hold the results of 2 ** x  
2) we copy those values into the y array

For very large arrays, it allows big **memory savings**

In [107]:
# use reduce() with np.*operator* to repeatdly apply operator
x = np.arange(1, 6)
np.add.reduce(x)

15

In [108]:
np.multiply.reduce(x)

120

In [109]:
# use accumulate() to store all the intermediate results
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [110]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [111]:
# use outer() to compute the output of all pairs
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

&nbsp;
<hr>

# <a id="4"></a>4. Computation using aggregations

&nbsp;
<hr>
<h1><a id="5"></a>5.</h1>

In [ ]:
# MATMUL

a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

In [ ]:
# STATS
# min
# max
# mean
# stdev

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)
np.max(stats, axis=1)
np.sum(stats, axis=0)

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

# Transpose
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

In [ ]:
# load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

In [ ]:
# Boolean Masking and Advanced Indexing
(~((filedata > 50) & (filedata < 100)))

&nbsp;
<hr>
<h1><a id="credits"></a>Credits</h1>

&nbsp;  


This notebook is in big part inspired by the work of [Jake Vanderplas](https://github.com/jakevdp/PythonDataScienceHandbook)

In [112]:
# nested lists
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])